import { createDaysOfWeek } from './render-week.js';
import { renderCalendar } from './render-calendar.js';
import { renderSidebar } from './sidebar.js';
import { displayCurrentWeek, switchWeekForward } from './display-current-week.js';
import {showPopup, closePopup, createPopup} from './create-popup.js';
import { displayEvents } from './displaying-events.js';
import { deleteEvent } from './delete-event.js';
import { durationValidation } from './validating-form.js';
import { saveNewEvent } from './save-event.js';
import { renderRedLine } from './redline.js';